export const applicationVideoCues = [
  {
    id: "01",
    title: "About Nicholas",
    url: "/about",
    startTime: 1,
    endTime: 68,
  },
  {
    id: "02",
    title: "My Story",
    url: "/video-experience",
    startTime: 1.5,
    endTime: 68,
  },

  {
    id: "99",
    title: "My Blog",
    url: "/https://nicholasegner.com/blog",
    startTime: 2,
    endTime: 68,
  },

  {
    id: "03",
    title: "Davis Defense Video Hub",
    url: "https://www.davisdefenselawyers.com/video",
    startTime: 67.5,
    endTime: 96,
  },

  {
    id: "04",
    title: "Davis Case Study",
    url: "https://nicholasegner.com/projects?project=davis-defense",
    startTime: 68,
    endTime: 96.5,
  },
  {
    id: "05",
    title: "Video SEO Notes",
    url: "https://docs.google.com/document/d/1DKUDjqn9KfHWh4lsZUzRlLlY0H90l2XhzBLTl1kqyW4/edit?usp=sharing",
    startTime: 95,
    endTime: 121,
  },
  {
    id: "06",
    title: "Video SEO Trifecta",
    url: "https://nicholasegner.com/blog/video-seo-trifecta",
    startTime: 108,
    endTime: 121,
  },
  {
    id: "07",
    title: "YWCA Event Content",
    url: "https://nciholasegner.s3.us-east-2.amazonaws.com/video/website-videos/YWCA-+Womans-Triathlon.mp4",
    startTime: 120,
    endTime: 145,
  },
  {
    id: "08",
    title: "Landscape Structures",
    url: "https://nicholasegner.com",
    startTime: 120,
    endTime: 145,
  },
  {
    id: "09",
    title: "Barlow Research Conference 2024",
    url: "https://nciholasegner.s3.us-east-2.amazonaws.com/video/website-videos/bbc.mp4",
    startTime: 120,
    endTime: 145,
  },
  {
    id: "10",
    title: "Your Gardens By Design",
    url: "https://nicholasegner.com/blog/your-gardens-by-design-video",
    startTime: 120,
    endTime: 145,
  },
  {
    id: "98",
    title: "Past Work Video Reel",
    url: "https://www.youtube.com/watch?v=7NM8T8zdUlU",
    startTime: 120,
    endTime: 145,
  },
  {
    id: "11",
    title: "LinkedIn",
    url: "https://www.linkedin.com/in/nicholas-egner/",
    startTime: 145,
    endTime: 270,
  },
  {
    id: "12",
    title: "Github",
    url: "https://github.com/egnica",
    startTime: 145,
    endTime: 270,
  },
  {
    id: "13",
    title: "YouTube",
    url: "https://www.youtube.com/@NicholasEgner",
    startTime: 145,
    endTime: 270,
  },
  {
    id: "14",
    title: "Spotify",
    url: "https://open.spotify.com/user/1224553002?si=c3d54db378354cf5&nd=1&dlsi=ffb896dd3c424f82",
    startTime: 145,
    endTime: 270,
  },
];
